content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

event/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

ozel2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('event/', include('event.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('aboutus', views.aboutus, name='aboutus'),
    path('references', views.references, name='references'),
    path('contact', views.contact, name='contact'),
    path('error', views.error, name='error'),

    path('category/<int:id>/<slug:slug>/', views.category_events, name='category_events'),
    path('event/<int:id>/<slug:slug>/', views.event_detail, name='event_detail'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('category/<int:id>', views.category, name='category'),
    path('announcments/<int:id>/<slug:slug>/', views.announcment_content, name='announcment_content'),

    path('search/', views.event_search, name='event_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('faq/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #adminde resimin görünmesini sağlar

user/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),

    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),


    path('addevent/', views.addevent, name='addevent'),
    path('events/', views.events, name='events'),   #contents list
    path('eventedit/<int:id>', views.eventedit, name='eventedit'),  #contentedit
    path('eventdelete/<int:id>', views.eventdelete, name='eventdelete'),
    path('eventaddimage/<int:id>', views.eventaddimage, name='eventaddimage'),

    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

content/models.py
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, FileInput, Select
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Menu(MPTTModel):
    STATUS =(
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=30, unique=True)
    status=models.CharField(max_length=10,choices=STATUS)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)  #self denildiği zaman kendi id si
    link = models.CharField(max_length=10, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_inserttion_by =['title']

    def __str__(self):
        full_path= [self.title]
        k= self.parent
        while k is not None:
            full_path.append(k.title)
            k=k.parent
        return ' -> '.join(full_path[::-1])

TYPE = (
    ('menu', 'menu'),
)
STATUS =(
     ('True', 'Evet'),
     ('False', 'Hayır'),
)

class Content(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    menu=models.OneToOneField(Menu,null=True,blank=True,on_delete=models.CASCADE)  #category olduğunda category_id si
    type = models.CharField(max_length=20, choices=TYPE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True,max_length=255)
    description = models.CharField(blank=True,max_length=255)
    image=models.ImageField(upload_to='images/')
    status=models.CharField(max_length=10,choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    detail=RichTextUploadingField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail',kwargs={'slug': self.slug})


class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['type','title','slug','keywords','description','image','detail']
        widgets = {
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'type': Select(attrs={'class': 'input', 'placeholder': 'city'},choices=TYPE),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),
        }



class CImages(models.Model):
    content = models.ForeignKey(Content,on_delete=models.CASCADE)  #baglı olduğu activite silindiğinde burada da silinmesi için
    title = models.CharField(max_length=80, blank=True)
    image = models.ImageField(blank=True,upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class ContentImageForm(ModelForm):
    class Meta:
        model = CImages
        fields = ['title', 'image']


class Commentt(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    content=models.ForeignKey(Content,on_delete=models.CASCADE) #baglı olduğu activite silindiğinde burada da silinmesi için
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=80, blank=True)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommenttForm(ModelForm):
    class Meta:
        model=Commentt
        fields=['subject','comment','rate']

event/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    STATUS =(
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=30)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image=models.ImageField(blank=True,upload_to='images/')
    status=models.CharField(max_length=10,choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)  #self denildiği zaman kendi id si
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_inserttion_by =['title']

    def __str__(self):
        full_path= [self.title]
        k= self.parent
        while k is not None:
            full_path.append(k.title)
            k=k.parent
        return ' -> '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail',kwargs={'slug':self.slug})

class Event(models.Model):
    STATUS =(
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)  #category olduğunda category_id si
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image=models.ImageField(blank=True,upload_to='images/')
    slug = models.SlugField(null=False, unique=True)
    status=models.CharField(max_length=10,choices=STATUS)
    detail=RichTextUploadingField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail',kwargs={'slug': self.slug})

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['category','title','slug','keywords','description','image','detail']
        widgets = {
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'category': Select(attrs={'class': 'input', 'placeholder': 'city'},choices=Category.objects.all()),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),
        }

class Images(models.Model):
    event=models.ForeignKey(Event,on_delete=models.CASCADE)  #baglı olduğu activite silindiğinde burada da silinmesi için
    title = models.CharField(max_length=80, blank=True)
    image=models.ImageField(blank=True,upload_to='images/')
    def __str__(self):
        return self.title
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class EventImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title', 'image']


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    event=models.ForeignKey(Event,on_delete=models.CASCADE) #baglı olduğu activite silindiğinde burada da silinmesi için
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=80, blank=True)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model=Comment
        fields=['subject','comment','rate']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query=forms.CharField(label='Search', max_length=100)

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label='User Name :')
    email = forms.EmailField(max_length=200,label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100,help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2',)

content/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from content.models import CommenttForm, Commentt


def index(request):
    return HttpResponse("Content Page")


@login_required(login_url='/login') #Check login
def addcomment (request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method=='POST':
        form=CommenttForm(request.POST)
        if form.is_valid():
            current_user=request.user
            data=Commentt()
            data.user_id=current_user.id
            data.content_id=id
            data.subject=form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip=request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request,"Yorumunuz basarılı bir şekilde gönderildi. Teşekkür ederiz.")
            return HttpResponseRedirect(url)

    messages.warning(request, "Yorumunuz kaydedilmedi. Lütfen kontrol edip tekrar deneyiniz.")
    return HttpResponseRedirect(url)

event/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from event.models import CommentForm, Comment


def index(request):
    return HttpResponse("Event Page")

@login_required(login_url='/login') #Check login
def addcomment (request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            current_user=request.user
            data=Comment()
            data.user_id=current_user.id
            data.event_id=id
            data.subject=form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip=request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request,"Yorumunuz basarılı bir şekilde gönderildi. Teşekkür ederiz.")
            return HttpResponseRedirect(url)

    messages.warning(request, "Yorumunuz kaydedilmedi. Lütfen kontrol edip tekrar deneyiniz.")
    return HttpResponseRedirect(url)

home/templates/aboutus.html
{% extends "homebase.html" %}

{% block title %} AboutUs {{ setting.company}} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block body %}


     <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>{{setting.title}}</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>

                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <aside>
                        <div class="widget">
                            <h4 class="heading-success"><span class="btn btn-large btn-success"><i class="m-icon-big-swapdown m-icon-white"></i></span>{{ setting.title }}&nbsp;&nbsp;Hakkımızda </h4>
                            <strong></strong><br><br>
                            <ul>
                                {{ setting.aboutus|safe }}
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </section>


    {% endblock %}

home/templates/event_detail.html
{% extends "homebase.html" %}

{% block title %} {{ events.title }} {% endblock %}
{% block keywords %} {{ events.keywords}} {% endblock %}
{% block description %} {{ events.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block body %}


    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>{{setting.title}}</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>
                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span6">
                    <div id="myCarousel" class="carousel slide testimonials">
                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="testimonial">
                                    <div data-thumb="{{ events.image.url }}" style="height: 360px" >
                                        <img src="{{ events.image.url }}" style="height: 360px; width: 750px" alt=""/>
                                        <blockquote>
                                            <p>
                                            <h2>{{events.title}}</h2>
                                            </p>
                                        </blockquote>
                                    </div>

                                </div>
                            </div>
                            {% for rs in images %}
                                <div class="item">
                                    <div class="testimonial">
                                        <div data-thumb="{{ events.image.url }}" style="height: 360px" >
                                            <img class="zoom" data-pretty="prettyPhoto" src="{{ rs.image.url }}" style="height: 360px; width: 750px" alt=""/>
                                            </a>
                                            <blockquote>
                                                <p>
                                                <h2>{{rs.title}}</h2>
                                                </p>
                                            </blockquote>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
                    </div>
                </div>
                <div class="span2"></div>

                <div class="span4">
                    <h2>{{ events.title }}</h2>
                    <div class="row">

                        <div >
                            <table class="table">
                                <tbody>

                                <tr>
                                    <td>{{ events.detail |safe }} </td>
                                </tr>
                                </tbody>

                            </table>
                            <ul class="post-meta"><li class="first"><i class="icon-user"></i> <span>{{events.user.first_name}}</span></li></ul>
                        </div>
                    </div>
                </div>
            </div>


            <!-- divider -->
            <div class="row">
                <div class="span12">
                    <div class="divider"></div>
                </div>
            </div>
            <!-- end divider -->

            <div class="row">
                <div class="span12">
                    <div class="tabbable"> <!-- Only required for left/right tabs -->
                        <ul class="nav nav-tabs">
                            <li ><a href="#tab1" data-toggle="tab">Announcement Detail</a></li>
                            <li class="active"><a href="#tab3" data-toggle="tab">Comments</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane " id="tab1">
                                <p>{{ events.detail | safe}}</p>
                            </div>

                            <div class="tab-pane active" id="tab3">
                                {% for rs in comments%}
                                    <ul class="media-list">
                                        <li class="media">

                                            <div class="media-body">
                                                <h6><i class="icon-user"></i>{{ rs.user.first_name }}</h6>
                                                <span>Post :{{ rs.create_at }}</span>
                                                <div >
                                                    <i class="icon-star{% if rs.rate < 5 %}-empty {% endif %}"></i>
                                                    <i class="icon-star{% if rs.rate < 4 %}-empty {% endif %}"></i>
                                                    <i class="icon-star{% if rs.rate < 3 %}-empty {% endif %}"></i>
                                                    <i class="icon-star{% if rs.rate < 2 %}-empty {% endif %}"></i>
                                                    <i class="icon-star{% if rs.rate < 1 %}-empty {% endif %}"></i>
                                                </div>
                                            <div>
                                                <h5>{{ rs.subject }}</h5>
                                                <p>{{ rs.comment }}</p>
                                            </div>
                                            </div>
                                        </li>

                                    </ul>
                                {% endfor %}


                                {% if messages %}
                                    <h3><b>Write your comment </b></h3>
                                    {% for message in messages %}
                                        <div class="alert alert-{{ message.tags }}" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                <form name="comment" action="/event/addcomment/{{ events.id }}" method="post" role="form" class="contactForm">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="span12 form-group">
                                            <div class="input-rating">
                                                <h4 class="text-uppercase" > Your Rating : &nbsp;</h4>
                                                <label class="checkbox inline">
                                                    <input type="radio" id="star5" name="rate" value="5"> <i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>                                               </label>
                                                <label class="checkbox inline">
                                                    <input type="radio" id="star4" name="rate" value="4"> <i class="icon-star-empty"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
                                                </label>
                                                <label class="checkbox inline">
                                                    <input type="radio" id="star3" name="rate" value="3"> <i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
                                                </label>
                                                <label class="checkbox inline">
                                                    <input type="radio" id="star2" name="rate" value="2"> <i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star"></i><i class="icon-star"></i>
                                                </label>
                                                <label class="checkbox inline">
                                                    <input type="radio" id="star1" name="rate" value="1"> <i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star-empty"></i><i class="icon-star"></i>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="span7">
                                            <div class="divider"></div>
                                        </div>

                                        <div class="span7 form-group">
                                            <input type="text" class="input-block-level" id="id_subject" name="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                                            <div class="validation"></div>
                                        </div>

                                        <div class="span7 form-group">
                                            <textarea class="input-block-level" id="id_comment" name="comment" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Comment"></textarea>
                                            <div class="validation"></div>

                                            <div style="text-align: center;">
                                                <input type="hidden" name="token" value="5" />
                                                {% if user.id is not None %}
                                                    <button class="btn btn-medium btn-success" type="submit">Send Comment </button>
                                                {% else %}
                                                    <li>
                                                        <a href="/login"><i class="icon-user"></i>&nbsp;If you want to a comment please login</a>
                                                    </li>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

home/templates/slider.html
{% load static %}

<section id="intro">
    <div class="jumbotron masthead">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="camera_wrap camera_black_skin" id="camera_wrap_2">
                        {% for rs in sliderdata %}

                            <div data-thumb="" data-src="{{ rs.image.url }}" style="height:194px; width:219px">
                                <div class="camera_caption fadeFromBottom">
                                    <a href="/event/{{ rs.id }}/{{ rs.slug }}" class=""><h2>{{ rs.title }}</h2></a>
                                    <div class="hidden-phone">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                    <!-- #camera_wrap_1 -->

                </div>
            </div>
        </div>
    </div>
</section>