ozel2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('event/', include('event.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('aboutus', views.aboutus, name='aboutus'),
    path('references', views.references, name='references'),
    path('contact', views.contact, name='contact'),
    path('error', views.error, name='error'),

    path('category/<int:id>/<slug:slug>/', views.category_events, name='category_events'),
    path('event/<int:id>/<slug:slug>/', views.event_detail, name='event_detail'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('category/<int:id>', views.category, name='category'),
    path('announcments/<int:id>/<slug:slug>/', views.announcment_content, name='announcment_content'),

    path('search/', views.event_search, name='event_search'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('faq/', views.faq, name='faq'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #adminde resimin görünmesini sağlar

user/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),

    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),


    path('addevent/', views.addevent, name='addevent'),
    path('events/', views.events, name='events'),   #contents list
    path('eventedit/<int:id>', views.eventedit, name='eventedit'),  #contentedit
    path('eventdelete/<int:id>', views.eventdelete, name='eventdelete'),
    path('eventaddimage/<int:id>', views.eventaddimage, name='eventaddimage'),

    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),

]

user/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe


class AddActivity(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    image=models.FileField(blank=True,upload_to='images/')
    detail = RichTextUploadingField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class AddActivityForm(ModelForm):
    class Meta:
        model = AddActivity
        fields = ['title','name','surname','image','status','detail']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, FileInput, Select,EmailInput, PasswordInput

from home.models import UserProfile
from user.models import AddActivity


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
        widgets = {
            'username'  : TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email'     : EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name'   : TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name'   : TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone','address','city','country','image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': TextInput(attrs={'class': 'input', 'placeholder': 'city'}),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from content.models import Menu, Content, ContentForm, ContentImageForm, CImages
from event.models import Category, Comment, EventForm, Event, EventImageForm, Images
from home.models import Setting, UserProfile
from user.forms import UserUpdateForm, ProfileUpdateForm
from user.models import AddActivityForm, AddActivity


def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    #return HttpResponse(profile)
    context = {'category': category,
               'menu': menu,
               'setting': setting,
               'profile': profile,
               }
    return render(request, "user_profile.html",context)


def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your account has been updated')
            return redirect('/user')

    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {'category': category,
                   'menu': menu,
                   'user_form': user_form,
                   'profile_form': profile_form
        }
        return render(request, 'user_update.html', context)

def change_password(request):
    if request.method=='POST':
        form =PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated')
            return redirect('/user')
        else:
            messages.error(request,'Please correct the error<br>'+str(form.errors))
            return redirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        menu = Menu.objects.all()
        return render(request, 'change_password.html',{
            'form':form,'category': category,'menu': menu})

@login_required(login_url='/login') #Check login
def comments(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user
    comments= Comment.objects.filter(user_id=current_user.id)
    context = {'category': category,
               'setting': setting,
               'menu': menu,
               'comments': comments,
               }
    return render(request, 'user_comments.html', context)

@login_required(login_url='/login') #Check login
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.error(request, 'Comment deleted..')
    return HttpResponseRedirect('/user/comments')




@login_required(login_url='/login')  # Check login
def addevent(request):
    if request.method == 'POST':
        form = EventForm(request.POST,request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Event()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.category = form.cleaned_data['category']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status= 'False'
            data.save()
            messages.success(request, 'Etkiliğiniz eklendi. Teşekkür ederiz.')
            return HttpResponseRedirect('/user/events')
        else:
            messages.warning(request, 'Etkinliğiniz eklenemedi. Lütfen kontrol edip tekrar deneyiniz.' + str(form.errors))
            return HttpResponseRedirect('/user/addevent')
    else:
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        category = Category.objects.all()
        form = EventForm()
        context = {'menu': menu,
                   'category': category,
                   'setting': setting,
                   'form': form, }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')  # Check login
def events(request):          #content list
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    category = Category.objects.all()
    current_user = request.user
    events = Event.objects.filter(user_id=current_user.id)  # eklenen etkinliklerin gösterilmesi
    context = {'menu': menu,
               'category': category,
               'setting': setting,
               'events': events, }
    return render(request, 'user_contents.html', context)


def eventdelete(request,id):
    current_user = request.user
    Event.objects.filter(id=id, user_id=current_user.id).delete()
    messages.error(request, 'Activity deleted..')
    return HttpResponseRedirect('/user/events')


def eventedit(request,id):
    events =Event.objects.get(id=id)
    if request.method == 'POST':
        form = EventForm(request.POST,request.FILES,instance=events)
        if form.is_valid():
            form.save()
            messages.success(request, 'Etkiliğiniz eklendi. Teşekkür ederiz.')
            return HttpResponseRedirect('/user/events')
        else:
            messages.warning(request, 'Etkinliğiniz eklenemedi. Lütfen kontrol edip tekrar deneyiniz.' + str(form.errors))
            return HttpResponseRedirect('/user/eventedit/'+str(id))
    else:
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        category = Category.objects.all()
        form = EventForm(instance=events)
        context = {'menu': menu,
                   'category': category,
                   'setting': setting,
                   'form': form, }
        return render(request, 'user_addcontent.html', context)


def eventaddimage(request,id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = EventImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.event_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Fotograf eklendi. Teşekkür ederiz.')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request,
                             'Fotograf eklenemedi. Lütfen kontrol edip tekrar deneyiniz.' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        events = Event.objects.get(id=id)
        images = Images.objects.filter(event_id=id)
        form = EventImageForm()
        context = {'events': events,
                   'images': images,
                   'form': form, }
        return render(request, 'content_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} {{profile.user.first_name}} {{ setting.company}} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block body %}

    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>USER Profile</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>

                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                {% include "user_panel.html" %}

                <div class="span9">

                    <div class="spacer30"></div>
                    <h4 class="heading-success"><i class="m-icon-big-swapdown m-icon-white"></i></h4>
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text"></th>
                            <th class="text">Name-Surname</th>
                            <th class="text">E-mail</th>
                            <th class="text">Phone</th>
                            <th class="text">Address</th>
                            <th class="text">City</th>
                            <th class="text">Country</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><img src="{{ user.userprofile.image.url }}" style="height: 50%"></td>
                        </tr>
                        </tbody>
                    </table>
                    <div style="text-align: center;">

                    {% if messages %}
                        {% for message in messages %}
                            {{ message|safe }}
                        {% endfor %}
                    {% endif %}

                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }}<br>

                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </p>
                            {% endfor %}
                            <div class="form-horizontal">
                                <button type="submit">Save Changed</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<body>
<h2>{{ content.title }}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    <div class="row">
        <div class="span6 form-group">
            {% csrf_token %}
            <input type="hidden" name="content_id" id="id_content_id" value="{{ content.id }}">
            <label for="id_title">Title:</label>
            <input type="text" name="title" class="input" placeholder="title" id="id_title"><br>
            <label for="id_image">Image:</label>
            <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image" ><br><br><br>
            <button class="primary" type="submit">Upload Image</button>
        </div>
    </div>
</form>
<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}
</body>

user/templates/user_addcontent.html
{% extends "homebase.html" %}

{% block title %} {{profile.user.first_name}} {{ setting.company}} {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% load static %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block body %}

    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>USER Profile</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>

                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                <ul class="breadcrumb">
                    <li><a href="/">HOME </a></li>
                    <li class="active"> / Create Activity Page</li>
                </ul>
                {% include "user_panel.html" %}

                <div class="span9">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="spacer30"></div>
                    <h4 class="heading-success"><i class="m-icon-big-swapdown m-icon-white"></i>NEW Create Activity</h4>

                    <form  enctype="multipart/form-data" method="POST" >
                        {% csrf_token %}
                        <fieldset class="form-horizontal">
                            {{ form.media }}
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-horizontal">
                            <button class="btn btn-medium btn-success" type="submit">Send Activity </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %} {{profile.user.first_name}} Comment Page {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block body %}

    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>USER Profile</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>

                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
            <ul class="breadcrumb">
                        <li><a href="/">HOME </a></li>
                        <li class="active"> / Comment</li>
                    </ul>
                {% include "user_panel.html" %}

                <div class="span9">
                 {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="spacer30"></div>
                    <h4 class="heading-success"><i class="m-icon-big-swapdown m-icon-white"></i></h4>
                    <table class="table">
                        <thead>
                        <tr>

                            <th class="text">Title</th>
                            <th class="text">Rate</th>
                            <th class="text">Subject</th>
                            <th class="text">Status</th>
                            <th class="text">Created At</th>
                            <th class="text">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for rs in comments %}
                            <tr>
                                <td class="text">
                                    <a href="/event/{{ rs.event.id }}/{{ rs.event.slug }}">
                                        {{ rs.event.title }}
                                    </a>
                                </td>
                                <td class="text">{{ rs.rate }}<i class="icon-star-empty"></i> </td>
                                <td class="text">{{ rs.subject }}</td>
                                <td class="text">{{ rs.status }}</td>
                                <td class="text">{{ rs.create_at }}</td>
                                <td class="text"><a href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Delete! Are you sure?')">Delete</a> </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/user_contents.html
{% extends "homebase.html" %}

{% block title %} {{profile.user.first_name}} Comment Page {% endblock %}
{% block keywords %} {{ setting.keywords}} {% endblock %}
{% block description %} {{ setting.description}} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}


{% block body %}

    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <h3><br><i class="m-icon-big-swapright m-icon-white"></i>USER Profile</h3>
                    </div>
                    <div class="span4">
                        <div class="input-append">
                            <form class="form-search" action="/search/" method="post">
                                {% csrf_token %}
                                <input type="text" name="query" class="input-medium search-query">
                                <button type="submit" class="btn btn-inverse">All Categories</button>
                                <ul class="social_small"><br>

                                    <li class="facebook first"><a href="{{setting.facebook}}" title="Facebook">Facebook</a></li>
                                    <li class="twitt"><a href="{{setting.twitter}}" title="Twitter">Twitter</a></li>
                                    <li class="googleplus"><a href="#" title="google plus">Google plus</a></li>
                                    <li class="flickr"><a href="#" title="flickr">Flickr</a></li>
                                    <li class="dribbble"><a href="#" title="Dribbble">Dribbble</a></li>
                                </ul>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="mainevents">
        <div class="container">
            <div class="row">
                <ul class="breadcrumb">
                    <li><a href="/">HOME </a></li>
                    <li class="active"> / eventss</li>
                </ul>
                {% include "user_panel.html" %}

                <div class="span9">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="spacer30"></div>
                    <h4 class="heading-success"><a href="/user/addevent" class="btn btn-medium btn-success">Create Activity </a>
                        <i class="m-icon-big-swapdown m-icon-white"></i></h4>
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text">Image</th>
                            <th class="text">Title</th>
                            <th class="text">Type</th>
                            <th class="text">Gallery</th>
                            <th class="text">Status</th>
                            <th class="text">Post</th>
                            <th class="text">Detail</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for rs in events  %}
                            <tr>
                                <td class="text"><a href="/events/{{ rs.id }}/{{ rs.slug }}">
                                    <img src="{{ rs.image.url }}" style="max-height: 100px;"></a></td>
                                <td class="text"><a href="/events/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></td>
                                <td class="text">{{ rs.category }}</td>
                                <td><a href="javascript:;" onclick="window.open('/user/eventaddimage/{{ rs.id }}', 'gallery','height=600,width=800,top=60,left=150')"><span class="btn btn-large "><i class="icon-camera"></i></span> </a></td>
                                <td class="text">{{ rs.status }}</td>
                                <td class="text">{{ rs.create_at }}</td>
                                <td class="text"><a href="/user/eventedit/{{ rs.id }}">EDIT</a> </td>
                                <td class="text"><a href="/user/eventdelete/{{ rs.id }}" onclick="return confirm('Delete! Are you sure?')">Delete</a> </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </section>

{% endblock %}